import './globals.css';
import type { Metadata } from 'next';
import Providers from './Providers';

import { Roboto } from 'next/font/google';

export const roboto = Roboto({
	subsets: ['latin'],
	weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className='dark'>
			<body className={roboto.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
